<template>
  <v-app>
    <div class="grid-container">
      <div class="grid-x grid-margin-x">
        <div class="cell">
          <h1>Mitrans Test</h1>
          <p>Product we're selling is below.
            <br>Send as much information as possible to Midtrans.
            <br>
            Cost of item is IDR {{ product.total.toLocaleString() }} which is in the currency Midtrans needs.
            <br>Adjust as needed.
          </p>
          <pre>{{ product }}</pre>
          <p>
            <button
              class="button primary"
              v-on:click="payWithMidtrans"
            >Pay IDR {{ product.total.toLocaleString() }}</button>
          </p>
        </div>
      </div>
    </div>
    <payment-modal :show="showModal" @onClose="showModal = false" :order-detail="orderDetail"></payment-modal>
  </v-app>
</template>

<script>
import PaymentModal from './PaymentModal'
import moment from 'moment'
export default {
  components: { PaymentModal },
  name: 'home',
  metaInfo: {
    title: 'Toorhop — Midtrans'
  },
  data () {
    return {
      product: {
        tour: 'Brooklyn Bridge Tour',
        name: 'Brooklyn Bridge Tour',
        description:
          'New Booking: Brooklyn Bridge Tour / December 25, 2019 / 4 / BOOKING_KEY',
        bookingKey: 'BOOKING_KEY',
        guideKey: 'GUIDE_KEY',
        tourKey: 'TOUR_KEY',
        travelerKey: 'TRAVELER_KEY',
        guideName: 'Spiderman',
        travelerName: 'Batman',
        requestedDate: '2019-12-25T12:00:00+7:00',
        adults: 4,
        total: 100000
      },
      showModal: false,
      orderDetail: {}
    }
  },
  methods: {
    payWithMidtrans () {
      /**
       * customer details
       * info of your costumers
       */
      const customerDetails = {
        email: 'example@example.com',
        first_name: 'first_name',
        last_name: 'last_name',
        phone: '08123456789'
      }

      /**
       * Array of your product detail to be sell
       */
      const itemDetails = [
        {
          id: moment().unix(),
          price: 25000,
          quantity: 4,
          name: this.product.name
        }
      ]

      /**
       * order_id as generated by your system
       */
      const orderId = moment().unix()

      this.orderDetail = {
        customer_details: customerDetails,
        item_details: itemDetails,
        order_id: orderId
      }
      this.showModal = true
    }
  }
}
</script>

<style lang="scss" scoped>
</style>
