import Vue from 'vue'
import VueI18n from 'vue-i18n'
import { store } from '@/store.js'

Vue.use(VueI18n)

const messages = {
  en: {
    tagline_first: 'Find Truly Unique Local Experiences',
    tagline_second: 'We connect travelers to passionate local experts',
    want_share: 'Want to share your favorite places and activities?',
    which_city: 'Which city are you visiting?',
    search: 'Search',
    become_guide: 'Become a Guide',
    toor_categories: 'Toor Categories',
    arts_culture: 'Arts & Culture',
    muslim_friendly: 'Muslim-friendly',
    outdoor_adventures: 'Outdoor Adventures',
    culinary: 'Culinary',
    sports: 'Sports',
    education: 'Education',
    family: 'Family',
    shopping: 'Shopping',
    nightlife_18: 'Nightlife (18+)',
    music_entertainment: 'Music & Entertainment',
    sightseeing: 'Sightseeing',
    business: 'Business',
    health: 'Health',
    photography: 'Photography',
    newest: 'Newest',
    most_popular: 'Most Popular',
    unique_offbeat: 'Unique & Offbeat',
    view_all_tours: 'View All Tours',
    testimonials: 'Testimonials',
    per_person: 'per person',
    hours: 'hour | hours',
    blog: 'Blog',
    dashboard: 'Dashboard',
    no_recent_activity: 'No recent activity found.',
    see_all_activity: 'See all activity',
    logout: 'Logout',
    edit_profile: 'Edit Profile',
    settings: 'Settings',
    register: 'Register',
    login: 'Login',
    faq: 'FAQ',
    contact: 'Contact',
    about: 'About',
    terms_of_service: 'Terms of Service',
    destination: 'Destination',
    category: 'Category',
    select: 'Select',
    language: 'Language',
    from: 'From',
    to: 'To',
    currency: 'Currency',
    find_a_toor: 'Find a Toor',
    no_matches_found: 'No matches found',
    we_found: 'We found',
    lowest_price: 'Lowest Price',
    longest_duration: 'Longest Duration',
    shortest_duration: 'Shortest Duration',
    hello_login_first: 'Hello, login first',
    welcome_back: 'Welcome Back!',
    guides_login_here: 'Guides login here',
    login_with_facebook: 'Login with Facebook',
    login_with_google: 'Login with Google',
    or: 'or',
    email: 'Email',
    password: 'Password',
    enter_valid_email: 'Enter a valid email address.',
    password_required: 'Password is required',
    new_password_required: 'New password is required',
    need_an_account: 'Need an account?',
    register_here: 'Register here',
    forgot_your_password: 'Forgot your password?',
    reset_password: 'Reset password',
    hello_register_first: 'Hello, register first',
    sign_up: 'Sign Up',
    have_you_setup: 'We’ll have you setup in no time!',
    guides_register_here: 'Guides register here',
    password_at_least: 'Password must have at least 6 characters.',
    passwords_must_be_identical: 'Passwords must be identical.',
    full_name: 'Full Name',
    repeat_password: 'Repeat Password',
    repeat_new_password: 'Repeat New Password',
    full_name_required: 'Full name is required',
    by_registering: 'By registering you agree to',
    registering: 'Registering',
    already_have_an_account: 'Already have an account?',
    forgot_password: 'Forgot password?',
    sending: 'Sending',
    login_here: 'Login here',
    terms_conditions: 'Terms & Conditions',
    my_tools: 'My Tools',
    upcoming: 'Upcoming',
    past_toors: 'Past Toors',
    messages: 'Messages',
    reviews: 'Reviews',
    hello: 'Hello',
    welcome_dashboard: 'Welcome to your dashboard!',
    none_found: 'None found',
    view_canceled: 'View Canceled',
    hide_canceled: 'Hide Canceled',
    confirmed: 'Confirmed',
    past_toor: 'Past Toor',
    requested: 'Requested',
    canceled: 'Canceled',
    info: 'Info',
    guests: 'Guests',
    date: 'Date',
    last_activity: 'Last activity',
    please_rate_review: 'Please take the time to rate and review this Toor. Your Toor Guide will really appreciate it!',
    rate_review: 'Rate & Review',
    your_rating: 'Your rating',
    your_review: 'Your review',
    how_would_you_rate: 'How would you rate this Toor?',
    rating: 'Rating',
    please_write_review: 'Please write your review here',
    cancel: 'Cancel',
    submit: 'Submit',
    account: 'Account',
    update_profile_settings: 'Update your profile and other account related settings',
    photo_instructions: 'Be sure to use a photo that clearly shows your face. This will help people identify you when they meet you for the toor.',
    upload_image: 'Upload Image',
    languages_spoken: 'Languages Spoken',
    describe_yourself: 'Describe Yourself',
    describe_yourself_tips: 'Help people get to know you. Tell them about the things you like and why you like being a Toor guide.',
    whatsapp_phone_number: 'WhatsApp or Mobile Number',
    go_to_dashboard: 'Go to Dashboard',
    save: 'Save',
    new_password: 'New Password',
    change_password: 'Change Password',
    linked_social_accounts: 'Linked Social Accounts',
    review: 'review | reviews',
    no_reviews: 'No reviews',
    share: 'Share',
    photo_by: 'Photo by',
    your_toor_guide: 'Your Toor Guide',
    ask_question: 'Ask Question',
    overview: 'Overview',
    toor_details: 'Toor Details',
    location: 'Location',
    duration: 'Duration',
    start_time: 'Start Time',
    price_per_person: 'Price per person',
    languages: 'Languages',
    transportation: 'Transportation',
    categories: 'Categories',
    where_will_toor_start: 'Where will Toor start?',
    exact_location: 'The guide will send you the exact location of the Toor once your booking is confirmed.',
    whats_included: 'What\'s Included?',
    excluded: 'Excluded',
    cancelation_policy: 'Cancelation Policy',
    cancelation_policy_explanation: 'Cancelations before 72 hours of your scheduled Toor incurs a 15% penalty. There is no refund for cancelations within 72 hours of scheduled Toor.',
    see_cancelation_policy: 'See our cancelation policy',
    total: 'Total',
    request_to_book: 'Request to Book',
    we_have_verified_toor: 'We have verified this Toor',
    hello_toorguide: 'Helloooo Toorguide!',
    ask_guide_hints: 'Ask your guide anything. (For example, request more specific info about where you’ll be meeting or what you’ll see.)',
    send_message: 'Send Message',
    close: 'Close',
    your_payment_details: 'Your Payment Details',
    how_want_pay: 'How do you want to pay?',
    use_cc_ending: 'Use credit card ending in',
    add_new_payment_method: 'Add a new payment method',
    card_number: 'Card Number',
    security_code: 'Security Code',
    expire_month: 'Expire Month',
    expire_year: 'Expire Year',
    cost_breakdown: 'Cost Breakdown',
    subtotal: 'Subtotal',
    convenience_fee: 'Convenience Fee',
    using_today: 'using today\'s',
    conversion_rate: 'conversation rate',
    you_wont_be_charged: 'You won’t be charged until your booking request is confirmed by your Toor guide.',
    view_cancelation_policy: 'View Cancellation Policy',
    book_now: 'Book Now',
    booking_requested: 'Booking Requested',
    what_happens_next: 'What happens next?',
    your_guide_will_review: 'Your Toor guide will review your booking request.',
    your_guide_notified: 'Your Toor guide has been notified of your booking details.',
    you_will_receive_confirmation: 'You will recieve a confirmation email within 24 hours.',
    once_toor_confirmed: 'Once the Toor is confirmed we will charge your credit card.',
    enjoy_the_toor: 'Enjoy the Toor!',
    booking_request: 'Booking Request',
    last_message: 'Last Message',
    view_all_past: 'View All Past',
    view_all_upcoming: 'View All Upcoming',
    message_guide: 'Message Guide',
    you_completed_this_toor: 'You completed this Toor on',
    time: 'Time',
    your_card_has_not_been_charged: 'Your card has not been charged yet. You can cancel this booking request, but let the guide know why.',
    cancel_booking_request: 'Cancel booking request',
    cancel_booking: 'Cancel Booking',
    cancel_request: 'Cancel Request',
    your_card_has_been_charged: 'Your card has been charged.',
    please_review_cancelation_policy: 'Please review our cancelation policy',
    or_contact_us_at: 'or contact us at',
    for_any_questions_or_concerns: 'for any questions or concerns',
    are_you_sure_cancel_booking: 'Are you sure you want to cancel this booking?',
    are_you_sure_cancel_booking_request: 'Are you sure you want to cancel the request?',
    please_let_us_know_why_canceling: 'Please let us know why you’re canceling',
    please_state_reason: 'Please state your reason for canceling',
    yes_understand_fees_canceling: 'Yes, I understand there are fees associated with canceling.',
    read_cancelation_policy: 'I’ve read the cancelation policy',
    yes_want_to_cancel: 'Yes, I want to cancel.',
    no: 'No',
    confirmed_toors: 'Confirmed Toors',
    no_scheduled_toors: 'No scheduled Toors.',
    no_messages_found: 'No messages found',
    no_reviews_found: 'No reviews found',
    notification_message_sent: 'Message sent!',
    notification_booking_request_canceled: 'Booking request canceled',
    notification_booking_canceled: 'Booking canceled',
    notification_review_submitted: 'Review submitted!',
    notification_profile_saved: 'Profile Saved',
    notification_uploading_image: 'Uploading image...',
    notification_image_updated: 'Profile image updated',
    notification_credit_card_updated: 'Credit card updated!',
    notification_booking_request_sent: 'Booking request sent!',
    toor_name: 'Toor Name',
    view_all_messages: 'View All Messages',
    waiting_for_reply: 'Waiting for Reply',
    respond: 'Respond',
    featured: 'Featured',
    any: 'Any',
    your_feedback_here: 'Your feedback here',
    how_do_you_like_toorhop: 'How do you like Toorhop?',
    submit_feedback: 'Submit Feedback',
    notification_submit_feedback: 'Thanks for your feedback!',
    about_us: 'About Us',
    contact_us: 'Contact Us',
    toors_by: 'Tours by',
    requested_date: 'Requested Date',
    credit_card_charged: 'Your credit card will be charged.',
    guide_will_be_in_touch: 'Your guide will be in touch with more information about your Toor.',
    discount_amount: 'Discount Amount',
    discount_total: 'Discount Total',
    discount: 'Discount',
    under_50: 'Under $50',
    under_100: 'Under $100',
    under_500: 'Under $500',
    over_500: 'Over $500',
    will_review_booking_request: 'We will review your booking request.',
    you_will_receive_confirmation_instructions: 'You will receive a confirmation email within 24 hours (excluding weekends).',
    you_will_have_twelve_hours: 'You will have 12 hours to accept and pay for your booking.',
    discount_code_applied: 'Discount code applied.',
    discount_code_error: 'Discount code does not exist, has expired, or has been already used.',
    discount_code_view_terms_conditions: 'View terms & conditions.',
    requests: 'Requests',
    city: 'City',
    country: 'Country',
    price: 'Price',
    account_settings: 'Account Settings',
    less_than_day: 'Less than a day',
    days_2_3: '2 to 3 days',
    days_4_7: '4 to 7 days',
    more_than_week: 'More than a week',
    go_to_booking_requests: 'Go to Booking Requests',
    booking_details: 'Booking Details',
    message: 'Message',
    our_partners: 'Our Partners',
    insurance: 'insurance',
    authorized_distributor_indonesia: 'authorized distributor in Indonesia'
  },
  id: {
    tagline_first: 'Temukan Beragam Pengalaman Lokal yang Unik dan Berbeda',
    tagline_second: 'Kami menghubungkan traveler dengan orang lokal yang berpengalaman bereksplorasi',
    want_share: 'Ingin membagikan tempat favorit dan aktivitasmu?',
    which_city: 'Kota mana yang akan kamu eksplorasi?',
    search: 'Cari',
    become_guide: 'Jadi ToorGuide',
    toor_categories: 'Kategori Toor',
    arts_culture: 'Seni & Budaya',
    muslim_friendly: 'Muslim-friendly',
    outdoor_adventures: 'Kegiatan Luar Ruang',
    culinary: 'Kuliner',
    sports: 'Olah Raga',
    education: 'Education',
    family: 'Keluarga',
    shopping: 'Belanja',
    nightlife_18: 'Kegiatan Malam (18+)',
    music_entertainment: 'Musik & Hiburan',
    sightseeing: 'Tamasya',
    business: 'Business',
    health: 'Health',
    photography: 'Photography',
    newest: 'Terbaru',
    most_popular: 'Paling Diminati',
    unique_offbeat: 'Unik & Tidak Biasa',
    view_all_tours: 'Lihat Semua Toors',
    testimonials: 'Testimoni',
    per_person: 'per orang',
    hours: 'jam | jam',
    blog: 'Blog',
    dashboard: 'Beranda',
    no_recent_activity: 'Tidak ada aktivitas terbaru',
    see_all_activity: 'Lihat semua aktivitas',
    logout: 'Keluar',
    edit_profile: 'Ubah Profil',
    settings: 'Pengaturan',
    register: 'Daftar',
    login: 'Masuk',
    faq: 'FAQ',
    contact: 'Kontak',
    about: 'Tentang',
    terms_of_service: 'Syarat & Ketentuan',
    destination: 'Destinasi',
    category: 'Kategori',
    select: 'Pilih',
    language: 'Bahasa',
    from: 'Dari',
    to: 'Ke',
    currency: 'Mata Uang',
    find_a_toor: 'Temukan Toor',
    no_matches_found: 'Tidak ditemukan yang kamu cari',
    we_found: 'Kita temukan',
    lowest_price: 'Harga Terendah',
    longest_duration: 'Durasi Terlama',
    shortest_duration: 'Durasi Terpendek',
    hello_login_first: 'Hai, Masuk Dahulu',
    welcome_back: 'Selamat Kembali!',
    guides_login_here: 'ToorGuide masuk disini',
    login_with_facebook: 'Masuk dengan Facebook',
    login_with_google: 'Masuk dengan Google',
    or: 'atau',
    email: 'Email',
    password: 'Kata sandi',
    enter_valid_email: 'Masukkan email yang benar',
    password_required: 'Perlu kata sandi',
    new_password_required: 'Perlu kata sandi baru',
    need_an_account: 'Perlu akun baru?',
    register_here: 'Daftar disini',
    forgot_your_password: 'Lupa kata sandimu?',
    reset_password: 'Bikin ulang kata sandimu',
    hello_register_first: 'Hai, Daftar Dulu, Yuk',
    sign_up: 'Daftar',
    have_you_setup: 'Kami akan mempersiapkanmu secepatnya!',
    guides_register_here: 'ToorGuide daftar disini',
    password_at_least: 'Kata sandi harus mengandung paling sedikit 6 huruf',
    passwords_must_be_identical: 'Kata sandi harus sama',
    full_name: 'Nama Lengkap',
    repeat_password: 'Ulang kata sandi',
    repeat_new_password: 'Ulang kata sandi baru',
    full_name_required: 'Perlu Nama Lengkap',
    by_registering: 'Dengan mendaftar kamu setuju ',
    registering: 'mendaftar',
    already_have_an_account: 'Sudah mempunyai akun?',
    forgot_password: 'Lupa kata sandimu?',
    sending: 'mengirim',
    login_here: 'masuk disini',
    terms_conditions: 'Syarat & Ketentuan',
    my_tools: 'Setelan',
    upcoming: 'Akan Datang',
    past_toors: 'Toor lalu',
    messages: 'pesan',
    reviews: 'Ulasan',
    hello: 'Hai',
    welcome_dashboard: 'Selamat datang di berandamu!',
    none_found: 'Tidak ada yang ditemukan',
    view_canceled: 'Lihat Pembatalan',
    hide_canceled: 'Sembunyikan Pembatalan',
    confirmed: 'Terkonfirmasi',
    past_toor: 'Toor lalu',
    requested: 'Diajukan',
    canceled: 'Dibatalkan',
    info: 'Info',
    guests: 'Tamu',
    date: 'Tanggal',
    last_activity: 'Aktivitas terakhir',
    please_rate_review: 'Silahkan luangkan waktu dan ulas Toor ini. ToorGuidemu akan sangat menghargainya!',
    rate_review: 'Nilai & Ulas',
    your_rating: 'Penilaianmu',
    your_review: 'Ulasanmu',
    how_would_you_rate: 'Bagaimana kamu menilai Toor ini?',
    rating: 'Penilaian',
    please_write_review: 'Tulis ulasanmu disini',
    cancel: 'Batal',
    submit: 'Ajukan',
    account: 'Akun',
    update_profile_settings: 'Perbarui profilmu dan pengaturan akun lainnya',
    photo_instructions: 'Pastikan kamu tampilkan wajahmu dengan jelas. Ini akan membantu traveler sewaktu menemuimu dalam Toor',
    upload_image: 'Upload gambar',
    languages_spoken: 'Bahasa',
    describe_yourself: 'Jelaskan dirimu',
    describe_yourself_tips: 'Bantu traveler tahu lebih mengenai dirimu. Ceritakan apa yang kamu suka dan mengapa kamu menikmati menjadi ToorGuide',
    whatsapp_phone_number: 'Nomor Whatsapp atau handphone',
    go_to_dashboard: 'Ke Beranda',
    save: 'Simpan',
    new_password: 'Kata sandi baru',
    change_password: 'Ganti kata sandi',
    linked_social_accounts: 'Akun sosial media yang terhubung',
    review: 'ulasan',
    no_reviews: 'tidak ada ulasan',
    share: 'Bagikan',
    photo_by: 'Foto oleh',
    your_toor_guide: 'ToorGuide-mu',
    ask_question: 'Tanya',
    overview: 'Ulasan Keseluruhan',
    toor_details: 'Detil Toor',
    location: 'Lokasi',
    duration: 'Durasi',
    start_time: 'Waktu Mulai',
    price_per_person: 'Harga per orang',
    languages: 'Bahasa',
    transportation: 'Transportasi',
    categories: 'Kategori',
    where_will_toor_start: 'Dimana Toor akan dimulai',
    exact_location: 'ToorGuide akan mengirimkanmu lokasi dari Toor dimulai setelah pesanan dikonfirmasi',
    whats_included: 'Termasuk Apa Saja?',
    excluded: 'Tidak Termasuk',
    cancelation_policy: 'Kebijakan Pembatalan',
    cancelation_policy_explanation: 'Pembatalan sebelum 72 jam dari jadwal Toormu akan dikenakan 15% penalti. Dana tidak akan dikembalikan untuk pembatalan setelah 72 jam dari Toor yang dikonfirmasi. Lihat kebijakan pembatalan kami.',
    see_cancelation_policy: 'Lihat kebjiakan pembatalan',
    total: 'Total',
    request_to_book: 'Permintaan untuk Pesan',
    we_have_verified_toor: 'Kami sudah memverifikasi Toor ini',
    hello_toorguide: 'Haiii, ToorGuide!',
    ask_guide_hints: 'Tanya ToorGuidemu apa saja. (Contoh, informasi spesifik dimana akan bertemu atau apa yang akan dilihat)',
    send_message: 'Kirim Pesan',
    close: 'Tutup',
    your_payment_details: 'Pembayaran detilmu',
    how_want_pay: 'Pilih cara pembayaranmu',
    use_cc_ending: 'Gunakan credit card yang diakhiri ',
    add_new_payment_method: 'Tambah metode pembayaran baru',
    card_number: 'Nomor kartu',
    security_code: 'Security Code',
    expire_month: 'Expire Month',
    expire_year: 'Expire Year',
    cost_breakdown: 'Rincian Biaya',
    subtotal: 'Subtotal',
    convenience_fee: 'Biaya kenyamanan',
    using_today: 'Gunakan hari ini',
    conversion_rate: 'konversi mata uang ',
    you_wont_be_charged: 'Kamu tidak akan dikenakan biaya sebelum permintaan pesanan dikonfirmasi oleh ToorGuide',
    view_cancelation_policy: 'Lihat kebjiakan pembatalan',
    book_now: 'Pesan Sekarang',
    booking_requested: 'Pesanan diajukan',
    what_happens_next: 'Apa Selanjutnya?',
    your_guide_will_review: 'ToorGuide akan mengulas permintaanmu',
    your_guide_notified: 'Your Toor guide has been notified of your booking details.',
    you_will_receive_confirmation: 'You will recieve a confirmation email within 24 hours.',
    once_toor_confirmed: 'Begitu Toor dikomfirmasi, kartumu akan di-charge',
    enjoy_the_toor: 'Nikmati Pengalamanmu!',
    booking_request: 'Ajukan Pesanan',
    last_message: 'Pesan Terakhir',
    view_all_past: 'Lihat semua yang lalu',
    view_all_upcoming: 'Lihat semua yang akan datang',
    message_guide: 'Hubungi ToorGuide',
    you_completed_this_toor: 'Kamu menyelesaikan Toor ini pada ',
    time: 'Waktu',
    your_card_has_not_been_charged: 'Kartumu belum kami charge. Kamu dapat membatalkan pengajuan pemesanan, tapi tolong infokan alsannya kepada Toorguide',
    cancel_booking_request: 'Batalkan Pengajuan Pesanan',
    cancel_booking: 'Batalkan Pesanan',
    cancel_request: 'Batalkan Pengajuan',
    your_card_has_been_charged: 'Kartumu sudah di-charge.',
    please_review_cancelation_policy: 'Silakan lihat kebijakan pembatalan kami ',
    or_contact_us_at: 'atau kontak kami di ',
    for_any_questions_or_concerns: 'untuk pertanyaan lainnya',
    are_you_sure_cancel_booking: 'Apakah kamu yakin mau membatalkan pesanan ini?',
    are_you_sure_cancel_booking_request: 'Apakah kamu yakin mau membatalkan pengajuan pesanan ini?',
    please_let_us_know_why_canceling: 'Sebutkan alasanmu untuk pembatalan',
    please_state_reason: 'Sebutkan alasanmu untuk pembatalan',
    yes_understand_fees_canceling: 'Ya, saya mengerti akan ada biaya mengenai pembatalan ',
    read_cancelation_policy: 'saya sudah membaca kebijakan pembatalan',
    yes_want_to_cancel: 'Ya, saya mau membatalkan',
    no: 'Tidak',
    confirmed_toors: 'Toor Terkonfirmasi',
    no_scheduled_toors: 'Tidak Ada Jadwal Toor',
    no_messages_found: 'Tidak Ada Pesan',
    no_reviews_found: 'Tidak Ada Ulasan',
    notification_message_sent: 'Pesan Terkirim!',
    notification_booking_request_canceled: 'Permintaan pesanan dibatalkan',
    notification_booking_canceled: 'Pesanan dibatalkan',
    notification_review_submitted: 'Ulasan diterima!',
    notification_profile_saved: 'Profile tersimpan',
    notification_uploading_image: 'Uploading gambar...',
    notification_image_updated: 'Gambar profil diperbaharui',
    notification_credit_card_updated: 'Credit card diperbaharui',
    notification_booking_request_sent: 'Permintaan pesanan terkirim!',
    toor_name: 'Toor Name',
    view_all_messages: 'View All Messages',
    waiting_for_reply: 'Waiting for Reply',
    respond: 'Respond',
    featured: 'Featured',
    any: 'Semua',
    your_feedback_here: 'Masukkan kamu disini',
    how_do_you_like_toorhop: 'Bagaimana kesanmu dengan Toorhop?',
    submit_feedback: 'Kirim Masukkanmu',
    notification_submit_feedback: 'Terima kasih untuk masukkanmu!',
    about_us: 'Tentang Kami',
    contact_us: 'Kontak Kami',
    toors_by: 'Tours by',
    requested_date: 'Requested Date',
    credit_card_charged: 'Your credit card will be charged.',
    guide_will_be_in_touch: 'Your guide will be in touch with more information about your Toor.',
    discount_amount: 'Discount Amount',
    discount_total: 'Discount Total',
    discount: 'Discount',
    under_50: 'Under $50',
    under_100: 'Under $100',
    under_500: 'Under $500',
    over_500: 'Over $500',
    will_review_booking_request: 'We will review your booking request.',
    you_will_receive_confirmation_instructions: 'You will receive a confirmation email within 24 hours (excluding weekends).',
    you_will_have_twelve_hours: 'You will have 12 hours to accept and pay for your booking.',
    discount_code_applied: 'Discount code applied.',
    discount_code_error: 'Discount code does not exist, has expired, or has been used.',
    discount_code_view_terms_conditions: 'View terms & conditions.',
    requests: 'Requests',
    city: 'City',
    country: 'Country',
    price: 'Price',
    account_settings: 'Account Settings',
    less_than_day: 'Less than a day',
    days_2_3: '2 to 3 days',
    days_4_7: '4 to 7 days',
    more_than_week: 'More than a week',
    go_to_booking_requests: 'Go to Booking Requests',
    booking_details: 'Booking Details',
    message: 'Message',
    our_partners: 'Our Partners',
    insurance: 'insurance',
    authorized_distributor_indonesia: 'authorized distributor in Indonesia'
  }
}

const i18n = new VueI18n({
  locale: store.getters.preferredLanguage,
  fallbackLocale: 'en',
  messages
})

export default i18n
